version: '2'
services:
    db:
        build: ./db
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        ports:
            - 3308:3306
        volumes:
            - sql-data:/var/lib/mysql

    app:
        build: ./app
        command: /go/bin/godo server --watch
        volumes:
            - ./app/src/myapp:/go/src/myapp
            - ./app/vendor:/go/src/
        ports:
            - 1323:1323
        links:
            - db

volumes:
  vendor:
  sql-data:
