version: '2'
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        ports:
            - 3308:3306
    web:
        build: .
        command: /go/bin/godo server --watch
        volumes:
            - ./myapp:/go/src/myapp
        ports:
            - 1323:1323
        depends_on:
            - db